# Generated by Django 6.0.7 on 2026-07-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_is_published_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attachment',
            field=models.FileField(blank=True, help_text='Any file: PDF, image, audio, document, etc.', null=True, upload_to='lecture_materials/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submission_link', models.URLField(blank=True, help_text='Link to Google Drive, GitHub, etc.', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
