# Generated by Django 5.2.16 on 2026-07-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_category_track_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_payment_intent_id",
            new_name="provider_transaction_id",
        ),
    ]
