# Generated by Django 5.2.16 on 2026-07-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0006_rename_stripe_payment_intent_id_payment_provider_transaction_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="courses.track",
            ),
        ),
        migrations.CreateModel(
            name="TrackRoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Used until a course is linked, or if none ever is.",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmap_steps",
                        to="courses.course",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_steps",
                        to="courses.track",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
