# Generated by Django 5.2.16 on 2026-07-14 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0009_alter_plan_options_plan_interval_subscriptionperiod_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchevent",
            name="occurred_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
