# Generated by Django 5.2.16 on 2026-07-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_watchevent_occurred_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
