# Generated by Django 5.2.16 on 2026-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_user_avatar_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="bunny_status",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lecture",
            name="bunny_video_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
