# Generated by Django 5.2.16 on 2026-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_lecture_bunny_status_lecture_bunny_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="accepts_submission",
            field=models.BooleanField(
                default=False, help_text="Students can upload homework for this lecture"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("student", "lecture")},
        ),
    ]
