# Generated by Django 5.2.16 on 2026-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_aiconversation_aimessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="description_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="track",
            name="name_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
