# Generated by Django 5.2.16 on 2026-07-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_track_description_translations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
