# Generated by Django 5.2.16 on 2026-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_certificate_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
