# Generated by Django 5.2.16 on 2026-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_user_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="description_translations",
        ),
        migrations.RemoveField(
            model_name="track",
            name="name_translations",
        ),
        migrations.AddField(
            model_name="course",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements_ar",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle_ar",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle_fr",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_will_learn_ar",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_will_learn_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_will_learn_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_will_learn_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.TextField(
                blank=True, default="", help_text="One feature per line."
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="features_ar",
            field=models.TextField(
                blank=True, default="", help_text="One feature per line.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="features_en",
            field=models.TextField(
                blank=True, default="", help_text="One feature per line.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="features_es",
            field=models.TextField(
                blank=True, default="", help_text="One feature per line.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="features_fr",
            field=models.TextField(
                blank=True, default="", help_text="One feature per line.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="track",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="track",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="track",
            name="name_fr",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
